version: '2'
services:
    homeassistant:
        build: hass
        user: 'hass:hass'
        group_add:
            - dialout
        container_name: hass
        image: homeassistant/home-assistant
        volumes: 
            - /shared/home-assistant/ha-config:/config
            - /etc/localtime:/etc/localtime:ro
        devices:
            - /dev/ttyACM0:/dev/zwave0:rwm
        network_mode: host
        depends_on:
            - mosquitto
            - node-red
            - nginx
        restart: unless-stopped
    mosquitto:
        build: mosquitto
        user: '1005:1005'
        container_name: MQTT
        image: eclipse-mosquitto
        volumes:
            - /shared/home-assistant/mqtt/data:/mosquitto/data
            - /shared/home-assistant/mqtt/config:/mosquitto/config:ro
            - /shared/home-assistant/mqtt/log:/mosquitto/log
            - /etc/localtime:/etc/localtime:ro
        network_mode: host
        restart: unless-stopped
    node-red:
        build: node-red-docker
        user: '1005:1005'
        container_name: node-red
        image: nodered/node-red-docker
        volumes:
            - /shared/home-assistant/node-red/data:/data
            - /etc/localtime:/etc/localtime:ro
        restart: unless-stopped
        network_mode: host
        ports:
            - "1880:1880"
    nginx:
        build: nginx-docker
        container_name: nginx
        image: nginx:latest
        volumes:
            - /shared/home-assistant/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
            - /shared/home-assistant/nginx/conf:/config
            - /shared/home-assistant/nginx/log:/var/log/nginx
            - /etc/localtime:/etc/localtime:ro
        network_mode: host



